---
name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - "src/Frontend/**"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git checkout -B gh-pages

          cp -r src/Frontend/*.html src/Frontend/assets/** .

          git add .
          git commit -m "Deploy to GitHub Pages"

          git push -u origin gh-pages
