---
name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - "src/Frontend/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Copy HTML and CSS files
        run: |
          mkdir gh-pages
          cp src/frontend/*.html gh-pages/
          cp src/frontend/*.css gh-pages/
          cp -R src/frontend/assets gh-pages/assets

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          cp -R gh-pages/* .
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Deploy latest HTML and CSS to gh-pages"
          git push
